---
- name: Install CUPS and drivers
  pacman:
    name: "{{ item }}"
  with_items:
    - ghostscript
    - gsfonts
    - cups
    - cups-pdf
    - gutenprint

- name: Install CUPS drivers from AUR
  aur:
    name: "{{ item}}"
    user: "{{ user.name }}"
  with_items:
    - cups-xerox
  tags:
    - aur

- name: Add a print admin group
  group:
    name: printadmin
    state: present

- name: Allow the print admin group to administer CUPS
  lineinfile:
    dest: /etc/cups/cups-files.conf
    regexp: "^SystemGroup"
    line: "SystemGroup sys root printadmin"
  notify:
    - restart cups

- name: Add the user to the print and print admin groups
  user:
    name: "{{ user.name }}"
    groups: printadmin,lp
    append: true
  tags:
    - user

- name: Enable and start CUPS
  service:
    name: org.cups.cupsd.service
    enabled: true
    state: started
