---
- name: Install Azure command-line tools
  aur:
    name: python-azure-cli
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install Azure Storage Explorer
  aur:
    name: storageexplorer
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install SQL Operations Studio
  aur:
    name: sqlops
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur
