---
- name: Install Azure command-line tools
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - python-azure-git  # python-azure is no longer maintained
    - python-azure-cli
  tags:
    - aur

- name: Install Azure Storage Explorer
  aur:
    name: storageexplorer
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install Azure Data Studio
  aur:
    name: azuredatastudio
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install Azure Storage Emulator
  aur:
    name: nodejs-azurite
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur
