---
language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev --system --skip-lock

script:
  - yamllint .
  - find playbooks -name \*yml -exec ansible-lint -v {} \;
