---
sudo: required
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --system --skip-lock

script:
  - yamllint .
  - cd playbooks && find -name \*yml -exec ansible-lint -v {} \;
