---
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

install:
  - pip install pipenv
  - pipenv install --dev --system --skip-lock

script:
  - yamllint .
  - bin/test-docker
