sudo: required

language: python
python:
  - "2.7"

services:
  - docker

install:
  - pip install pipenv
  - pipenv install --dev

before_script: chmod +x test-docker.sh

script: pipenv run ./test-docker.sh
