---
sudo: required
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install poetry
  - poetry install

script:
  - poetry run yamllint .
  - cd playbooks && find -name \*yml -exec poetry run ansible-lint -v {} \;
