---
- hosts: localhost
  become: "yes"
  roles:
    - { role: timezone, tags: ['timezone'] }
    - { role: locale, tags: ['locale'] }
    - { role: hostname, tags: ['hostname'], when: "hostname is defined and hostname != ''" }
    - { role: mkinitcpio, tags: ['mkinitcpio'] }
  vars_prompt:
    - name: hostname
      prompt: "Enter the desired hostname"
      private: no