---
- name: Install GDM and Plymouth
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - plymouth
    - gdm-plymouth
    - plymouth-theme-arch-logo

- name: Enable Plymouth GDM
  systemd:
    name: gdm-plymouth.service
    enabled: true

- name: Install Plymouth hook
  replace:
    path: /etc/mkinitcpio.conf
    regexp: 'HOOKS=\(base udev (?!plymouth)'
    replace: 'HOOKS=(base udev plymouth '
  notify: mkinitcpio

- name: Test current Plymouth theme
  command: plymouth-set-default-theme
  register: plymouth_theme
  changed_when: false
  check_mode: false

- name: Set plymouth theme
  command: plymouth-set-default-theme arch-logo -R
  when: plymouth_theme.stdout != 'arch-logo'

- name: Enable quiet boot
  replace:
    path: /boot/loader/entries/arch.conf
    regexp: '(^options(\s+(?!quiet splash udev\.log_priority=3)[\w=\-\.\,\_]+)*)\s*$'
    replace: '\1 quiet splash udev.log_priority=3'
