---
- name: Install vscode
  aur:
    name: visual-studio-code-bin
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install extension dependencies
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - shfmt

- name: install extensions
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ vscode.extensions }}"
  command: "code --install-extension '{{ item }}'"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
