---
- name: Install bluetooth libraries and tools
  pacman:
    name:
      - pulseaudio-bluetooth
      - bluez
      - bluez-libs
      - bluez-utils
      - blueman
  notify:
    - restart pulse as user

- name: Unblock the bluetooth service
  systemd:
    name: "rfkill-block@bluetooth.service"
    enabled: false
    state: stopped
  when: not bluetooth.disable

- name: Enable and start the bluetooth service
  systemd:
    name: bluetooth.service
    enabled: true
    state: started
  when: not bluetooth.disable

- name: Disable and stop the bluetooth service
  systemd:
    name: bluetooth.service
    enabled: false
    state: stopped
  when: bluetooth.disable

- name: Block the bluetooth service
  systemd:
    name: "rfkill-block@bluetooth.service"
    enabled: true
    state: started
  when: bluetooth.disable
