---
- name: restart pulse as user
  systemd:
    name: pulseaudio.service
    user: true
    state: restarted
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
