---
- name: Install k8s CLI tools
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - kubectl-bin
    - kubernetes-helm
    - skaffold
    - k9s-bin
    - kubectx
  tags:
    - aur

- name: Install k3s
  aur:
    name: k3s-bin
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur
