---
- name: Install k8s CLI tools
  pacman:
    name:
      - kubectl
      - kubectx
      - k9s
      - helm

- name: Install kind
  aur:
    name: kind
  become: true
  become_user: '{{ user.name }}'
  tags:
    - aur
