---
- name: Install kubectl
  aur:
    name: kubectl-bin
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install minikube
  aur:
    name: minikube-bin
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install helm
  aur:
    name: kubernetes-helm
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install skaffold
  aur:
    name: skaffold
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur
