---
- name: Install texlive-most
  pacman:
    name: texlive-most

- name: Install required fonts
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - otf-montserrat
    - ttf-font-awesome-4

- name: Install dependencies for latexindent
  aur:
    name: texlive-latexindent-meta
  become: true
  become_user: "{{ user.name }}"
