---
- name: Install texlive-most
  pacman:
    name: texlive-most

- name: Install required fonts
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - otf-montserrat
    - ttf-font-awesome-4
