---
- name: Install LibreOffice
  pacman:
    name: libreoffice-fresh

- name: Install LibreOffice language packs
  pacman:
    name: "{{ item }}"
  with_items:
    - libreoffice-fresh-en-gb
    - libreoffice-fresh-da

- name: Jail LibreOffice
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/libreoffice
    state: link
  tags:
    - firejail
