---
- include: libreoffice.yml
- include: latex.yml

- name: Install pandoc
  pacman:
    name: pandoc

- name: Install masterpdfeditor
  aur:
    name: masterpdfeditor-free
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur
