---
- name: Install IntelliJ IDEA
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - intellij-idea-ultimate-edition
    - intellij-idea-ultimate-edition-jre
  tags:
    - aur

- include: plugins.yml
