---
- name: Install NVIDIA drivers
  pacman:
    name: "{{ item }}"
  with_items:
    - nvidia
    - nvidia-utils
    - lib32-nvidia-utils

- name: Install NVIDIA settings
  pacman:
    name: nvidia-settings
