---
- name: Install ufw
  pacman:
    name: ufw
  tags:
    - firewall

- name: Enable and start ufw systemd service
  systemd:
    name: ufw.service
    enabled: true
    state: started
  tags:
    - firewall

- name: Enable ufw
  ufw:
    state: enabled
    policy: deny
  tags:
    - firewall

- name: Add custom ufw rules
  template:
    src: custom.j2
    dest: /etc/ufw/applications.d/custom
  tags:
    - firewall

- name: Allow SSH
  ufw:
    rule: limit
    name: my-SSH
  tags:
    - firewall
