---
- name: Disabling GNOME Shell top left hot corner
  aur:
    name: gnome-shell-extension-no-topleft-hot-corner
  become: true
  become_user: "{{ user.name }}"
  when: "gnome.gnome_shell.disable_top_left_hot_corner"
  tags:
    - aur

- name: Enabling GNOME Shell top left hot corner
  pacman:
    name: gnome-shell-extension-no-topleft-hot-corner
    state: absent
  when: "not gnome.gnome_shell.disable_top_left_hot_corner"

- name: Configuring GNOME Shell Extensions support
  pacman:
    name:
      - gnome-shell-extensions
      - chrome-gnome-shell
    state: '{{ "present" if gnome.gnome_shell.extensions_support else "absent" }}'

- name: Install GNOME shell extensions
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ gnome.extensions.packages }}"
  tags:
    - aur

- name: Enable GNOME shell extensions
  command: gnome-shell-extension-tool -e {{ item }}
  register: gnome_extension
  changed_when: "'is now enabled' in gnome_extension.stdout"
  failed_when: false
  loop: "{{ gnome.extensions.enabled }}"
  become: true
  become_user: "{{ user.name }}"
