---
# Using the builtin pacman module is not possible
# because gdm-plymouth conflicts with gdm
- name: Install GNOME
  pacman:
    name: gnome

- name: Install GNOME themes
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - paper-icon-theme-git
    - adapta-gtk-theme-git
  tags:
    - aur

- include: dconf.yml
- include: gtk.yml
- include: extensions.yml
- include: online_accounts.yml
