---
- name: Install GNOME
  pacman:
    name: gnome

- name: Install GNOME themes
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  with_items:
    - paper-icon-theme-git
    - adapta-gtk-theme-git
  tags:
    - aur

- name: Install wallpaper
  copy:
    src: wallpaper.jpg
    dest: /usr/share/backgrounds/wallpaper.jpg

- include: dconf.yml
- include: gtk.yml
- include: extensions.yml
- include: online_accounts.yml
