---
- name: Install GNOME
  pacman:
    name: gnome

- name: Install GNOME tweaks
  pacman:
    name: gnome-tweaks

- name: Install GNOME themes
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - paper-icon-theme-git
    - plata-theme
  tags:
    - aur

- name: Install wallpaper
  copy:
    src: background.jpg
    dest: /usr/share/backgrounds/background.jpg

- name: Copy avatar
  copy:
    src: face.png
    dest: "/home/{{ user.name }}/.face"

- name: Apply blueman workaround
  copy:
    src: 90-nopasswd_blueman.rules
    dest: /etc/polkit-1/rules.d/90-nopasswd_blueman.rules
  tags:
    - blueman

- include: dconf.yml
- include: gtk.yml
- include: extensions.yml
- include: online_accounts.yml
