---
- name: Install networkmanager-openvpn
  pacman:
    name: networkmanager-openvpn

- name: Get PIA CA certificate
  get_url:
    url: "https://www.privateinternetaccess.com/openvpn/ca.rsa.4096.crt"
    dest: "/etc/openvpn/pia-ca.rsa.4096.crt"

- name: Fetch PIA servers
  uri:
    url: "https://www.privateinternetaccess.com/vpninfo/servers"
    body_format: json
    return_content: true
    headers:
      Content-Type: "application/json"
  register: pia_servers

- name: Filter servers
  set_fact:
    pia_servers: "{{ pia_servers.content.split('\n')[0] | from_json | json_query('*.[dns, name]')  }}"

- name: Create NetworkManager connections
  template:
    src: pia.nmconnection.j2
    dest: "/etc/NetworkManager/system-connections/PIA - {{ pia_server[1] }}.nmconnection"
    owner: root
    group: root
    mode: 0600
  vars:
    pia_server: "{{ item }}"
  loop: "{{ pia_servers }}"
  notify: Restart NetworkManager
