---
- hosts: localhost
  become: true
  roles:
    - { role: timezone, tags: ['timezone'] }
    - { role: locale, tags: ['locale'] }
    - { role: hostname, tags: ['hostname'], when: "hostname is defined and hostname != ''" }
    - { role: mkinitcpio, tags: ['mkinitcpio'] }
    - { role: systemd-boot, tags: ['systemd-boot'], when: "systemd_boot is defined" }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: base, tags: ['base'] }
    - { role: vscode, tags: ['vscode'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: java, tags: ['java'] }
  vars_prompt:
    - name: user_password
      prompt: "Enter desired user password"
    - name: hostname
      prompt: "Enter the desired hostname"
      private: false
