---
- name: Install Chrome
  aur:
    name: google-chrome-dev
  become: true
  become_user: "{{ user.name }}"
  tags:
    - chrome

- name: Jail Chrome
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/google-chrome-unstable
    state: link
  tags:
    - chrome
    - firejail

- name: Copy Chrome desktop file
  copy:
    src: /usr/share/applications/google-chrome-unstable.desktop
    dest: "/home/{{ user.name }}/.local/share/applications/google-chrome-unstable.desktop"

- name: Jail Chrome desktop file
  lineinfile:
    path: "/home/{{ user.name }}/.local/share/applications/google-chrome-unstable.desktop"
    regexp: "Exec=/usr/bin/google-chrome-unstable %U"
    line: "Exec=google-chrome-unstable %U"

- name: Install shutdown hook
  aur:
    name: chrome-shutdown-hook
  become: true
  become_user: "{{ user.name }}"
  tags:
    - chrome
