---
# Most recent LTS releases (OpenJDK and Oracle)
- name: Install OpenJDK Java 8
  pacman:
    name: jdk8-openjdk
  tags:
    - java

- name: Install Oracle Java 8
  aur:
    name: jdk8
  become: true
  become_user: '{{ user.name }}'
  tags:
    - aur
    - java

# Current release
- name: Install OpenJDK 11
  pacman:
    name: jdk-openjdk
  tags:
    - java

# Next release
- name: Install OpenJDK 12
  aur:
    name: openjdk-devel
  become: true
  become_user: '{{ user.name }}'
  tags:
    - aur
    - java

- name: Check current default JDK
  command: archlinux-java get
  check_mode: false
  changed_when: false
  register: default_jdk
  tags:
    - java

- name: Set default JDK
  command: archlinux-java set java-8-jdk
  when: "default_jdk.stdout != 'java-8-jdk'"
  tags:
    - java

- name: Install Maven
  pacman:
    name: maven
  tags:
    - java

- name: Install Gradle
  pacman:
    name: gradle
  tags:
    - java

- name: Install Jetty
  aur:
    name: jetty
  become: true
  become_user: '{{ user.name }}'
  tags:
    - aur
    - java

- name: Install GraalVM
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - graal-bin
    - graalpython-bin
    - truffleruby-bin
    - fastr-bin
  tags:
    - aur
