---
# Most recent LTS releases (OpenJDK and Oracle)
- name: Install OpenJDK Java 8
  pacman:
    name: "{{ item }}"
  with_items:
    - jdk8-openjdk
    - openjdk8-doc
    - openjdk8-src

- name: Install Oracle Java 8
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - jdk8
    - jdk8-docs
  tags:
    - aur

# Current release
- name: Install OpenJDK 10
  pacman:
    name: "{{ item }}"
  with_items:
    - jdk10-openjdk
    - openjdk10-doc
    - openjdk10-src

# Next release
- name: Install Oracle Java 11
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - jdk-devel
    - jdk-devel-docs
  tags:
    - aur

- name: Check current default JDK
  command: archlinux-java
  check_mode: false
  changed_when: false
  register: default_jdk

- name: Set default JDK
  command: archlinux-java set java-8-jdk
  when: "default_jdk.stdout != 'java-8-jdk'"

- name: Install Maven
  pacman:
    name: maven

- name: Install Gradle
  pacman:
    name: "{{ item }}"
  with_items:
    - gradle
    - gradle-doc
    - gradle-src
