---
# OpenJDK 8
- name: Install OpenJDK Java 8
  pacman:
    name: "{{ item }}"
  loop:
    - jdk8-openjdk
    - openjdk8-doc
    - openjdk8-src
  tags:
    - java

# Current release
# LTS release
- name: Install OpenJDK 11
  pacman:
    name: "{{ item }}"
  loop:
    - jdk-openjdk
    - openjdk-doc
    - openjdk-src
  tags:
    - java

# Next release
- name: Install OpenJDK 12
  aur:
    name: "{{ item }}"
  loop:
    - java-openjdk-ea-bin
  become: true
  become_user: '{{ user.name }}'
  tags:
    - aur
    - java

- name: Check current default JDK
  command: archlinux-java get
  check_mode: false
  changed_when: false
  register: default_jdk
  tags:
    - java

- name: Set default JDK
  command: archlinux-java set java-8-openjdk
  when: "default_jdk.stdout != 'java-8-openjdk'"
  tags:
    - java

- name: Install Maven
  pacman:
    name: maven
  tags:
    - java

- name: Install Gradle
  pacman:
    name: gradle
  tags:
    - java

- name: Install Jetty
  aur:
    name: jetty
  become: true
  become_user: '{{ user.name }}'
  tags:
    - aur
    - java
