---
- name: Install NetworkManager PPTP plugin
  pacman:
    name: networkmanager-pptp

- name: Clone VPN setup git repo
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: "{{ work.vpn.repo }}"
    dest: "/home/{{ user.name }}/work/vpn"
    accept_hostkey: true
    version: "master"
