---
- name: Install NetworkManager OpenConnect plugin
  pacman:
    name: networkmanager-openconnect

- name: Clone VPN setup git repo
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: "{{ work.vpn.repo }}"
    dest: "/home/{{ user.name }}/work/vpn"
    accept_hostkey: true
    version: "master"

- name: Copy MSFTVPN configuration
  template:
    src: MSFTVPN.nmconnection.j2
    dest: /etc/NetworkManager/system-connections/MSFTVPN.nmconnection
    owner: root
    group: root
    mode: 0600
  notify: Restart NetworkManager

- name: Use msftvpn for auth
  lineinfile:
    path: /usr/lib/NetworkManager/VPN/nm-openconnect-service.name
    regexp: "^auth-dialog="
    line: "auth-dialog=/usr/bin/msftvpn"
