---
- name: Install stubby
  pacman:
    name: stubby

- name: Install stubby config
  copy:
    src: stubby.yml
    dest: /etc/stubby/stubby.yml

- name: Start and enable stubby service
  systemd:
    name: stubby.service
    enabled: true
    state: started
    daemon_reload: true

- name: Install dnsmasq
  pacman:
    name: dnsmasq

- name: test
  file:
    path: /etc/NetworkManager/dnsmasq.d
    state: directory

- name: Install dnsmasq config
  copy:
    src: dnsmasq.conf
    dest: /etc/NetworkManager/dnsmasq.d/dnsmasq.conf

- name: Jail dnsmasq
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/dnsmasq
    state: link
  notify: Restart NetworkManager
  tags:
    - firejail
