---
- name: Install Unbound
  pacman:
    name: unbound

- name: Download root hints
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
    force: true

- name: Copy Unbound configuration file
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf

- name: Create Unbound systemd unit file directory
  file:
    path: /etc/systemd/system/unbound.service.d
    state: directory
  tags:
    - firejail

- name: Push Unbound socket unit file
  copy:
    src: unbound-service-override.conf
    dest: /etc/systemd/system/unbound.service.d/override.conf
  tags:
    - firejail

- name: Remove Unbound systemd unit PID file line
  lineinfile:
    dest: /usr/lib/systemd/system/unbound.service
    state: absent
    line: 'PIDFile=/run/unbound.pid'
  tags:
    - firejail

- name: Push resolvconf.conf
  copy:
    src: resolvconf.conf
    dest: /etc/resolvconf.conf

- name: Restart NetworkManager
  systemd:
    name: NetworkManager.service
    state: restarted

- name: Push root hints update service
  copy:
    src: roothints.service
    dest: /etc/systemd/system/roothints.service

- name: Push root hints update timer
  copy:
    src: roothints.timer
    dest: /etc/systemd/system/roothints.timer

- name: Enable and start root hints update timer
  systemd:
    name: roothints.timer
    enabled: true
    state: started
    daemon_reload: true

- name: Enable and start Unbound
  service:
    name: unbound.service
    enabled: true
    state: restarted
    daemon_reload: true

- name: Pause while unbound starts up
  pause:
    seconds: 10
