---
- name: Install VirtualBox and dependencies
  pacman:
    name: "{{ item }}"
  with_items:
    - virtualbox
    - virtualbox-guest-iso
    - virtualbox-host-modules-arch

- name: Install VirtualBox extensions
  aur:
    name: virtualbox-ext-oracle
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Add the user to vboxusers group
  user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: true
  tags:
    - user
