---
- name: Install VirtualBox and dependencies
  pacman:
    name:
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-dkms

- name: Install VirtualBox extensions
  aur:
    name: virtualbox-ext-oracle
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Add the user to vboxusers group
  user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: true
  tags:
    - user
