---
- name: Install Node.js
  pacman:
    name: nodejs

- name: Install package managers
  pacman:
    name:
      - npm
      - yarn

- name: Install task runners
  pacman:
    name:
      - gulp
      - grunt-cli
