---
- name: Install Node.js
  pacman:
    name: nodejs

- name: Install package managers
  pacman:
    name: "{{ item }}"
  with_items:
    - npm
    - yarn

- name: Install task runners
  pacman:
    name: "{{ item }}"
  with_items:
    - gulp
    - grunt-cli
