---
- name: Install LightDM
  pacman:
    name: lightdm

- name: Install LightDM greeter
  aur:
    name: lightdm-webkit2-greeter
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install LightDM theme
  aur:
    name: lightdm-webkit-theme-litarvan
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Copy LightDM Webkit greeter settings
  copy:
    src: lightdm-webkit2-greeter.conf
    dest: /etc/lightdm/lightdm-webkit2-greeter.conf
    group: root
    owner: root
    mode: 0644

- name: Enable LightDM
  systemd:
    name: lightdm.service
    enabled: true

- name: Enable quiet boot
  replace:
    path: /boot/loader/entries/arch.conf
    regexp: '(^options(\s+(?!quiet splash udev\.log_priority=3)[\w=\-\.\,\_]+)*)\s*$'
    replace: '\1 quiet splash udev.log_priority=3'

- name: Change LightDM background
  copy:
    src: background.jpg
    dest: /usr/share/lightdm-webkit/themes/litarvan/images/background.jpg
