---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-en_GB
  tags:
    - hunspell

- name: Install hunspell AUR packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - hunspell-da
  tags:
    - hunspell
    - aur

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
  tags:
    - aspell

- name: Install aspell AUR packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - aspell-da
  tags:
    - aspell
    - aur
