---
- name: Install hunspell
  pacman:
    name: "{{ item }}"
  with_items:
    - hunspell
    - hunspell-en
  tags:
    - hunspell

- name: Install hunspell AUR packages
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - hunspell-da
  tags:
    - hunspell
    - aur

- name: Install aspell
  pacman:
    name: "{{ item }}"
  with_items:
    - aspell
    - aspell-en
  tags:
    - aspell

- name: Install aspell AUR packages
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - aspell-da
  tags:
    - aspell
    - aur
