---
- name: Install kdenlive
  aur:
    name: kdenlive
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install breeze icons
  pacman:
    name: breeze-icons

- name: Jail kdenlive
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/kdenlive
    state: link
  tags:
    - firejail
