---
- include: spotify.yml
- include: vlc.yml
- include: gimp.yml
- include: kdenlive.yml

- name: Install youtube-dl
  pacman:
    name: youtube-dl

- name: Install peek
  aur:
    name: peek
  become: true
  become_user: "{{ user.name }}"
