---
- name: Install zip archive utilities
  pacman:
    name:
      - zip
      - unzip
      - p7zip
  tags:
    - zip

- name: Install unrar
  pacman:
    name: unrar
  tags:
    - unrar

- name: Install atool
  pacman:
    name: atool
  tags:
    - atool

- name: Install hashdeep
  pacman:
    name: hashdeep
  tags:
    - hashdeep

- name: Install par2cmdline
  pacman:
    name: par2cmdline
  tags:
    - par2

- name: Install ddrescue
  pacman:
    name: ddrescue
  tags:
    - ddrescue

- name: Install lesspipe
  pacman:
    name: lesspipe
  tags:
    - lesspipe
