---
- name: Install docker
  pacman:
    name: docker

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  tags:
    - user

- name: Override docker default subnet
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Enable and start docker service
  systemd:
    name: docker.service
    enabled: true
    state: started
