---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Refresh pacman mirrors
  pacman: 
    update_cache: yes

- include: user.yml
- include: shell.yml
- include: sudo.yml
- include: packages.yml
- include: journal.yml
