---
- name: Refresh package list and upgrade system
  pacman:
    upgrade: true
    update_cache: true
  tags:
    - packages

- name: Install universal base packages
  pacman:
    name: "{{ base_packages }}"
  tags:
    - packages

- name: Create pacman hook directory
  file:
    path: /etc/pacman.d/hooks
    state: directory
  tags:
    - packages

- name: Use all cores when compressing packages
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: "^COMPRESSXZ"
    line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Install AUR base packages
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ aur.packages }}"
  tags:
    - aur
    - packages

- name: Push pacman cache cleanup service
  copy:
    src: paccache.service
    dest: /etc/systemd/system/paccache.service
  tags:
    - packages

- name: Push pacman cache cleanup timer
  copy:
    src: paccache.timer
    dest: /etc/systemd/system/paccache.timer
  notify:
    - restart paccache
  tags:
    - packages

- name: Enable and start pacman cache cleanup timer
  systemd:
    name: paccache.timer
    enabled: true
    state: started
    daemon_reload: true
  tags:
    - packages
