---
- name: Install fish shell
  pacman:
    name: fish

- name: Install fisher
  aur:
    name: fisher
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install fisher packages
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ fisher.packages }}"
  command: /usr/bin/fish -c 'fisher add "{{ item }}"'
  register: fisher_packages
  changed_when: "'added 1 package' in fisher_packages.stdout"
