---
- name: Install fish shell
  pacman:
    name: fish

- name: Install fisher
  aur:
    name: fisher
  become: true
  become_user: "{{ user.name }}"
  tags:
    - aur

- name: Install fisher packages
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ fisher.packages }}"
  command: /usr/bin/fish -c 'fisher add "{{ item }}"'
  register: fisher_result
  changed_when: "'No plugins to install or dependencies missing.' not in fisher_result.stderr"
