---
- name: Create user group
  group:
    name: "{{ user.group }}"
  tags:
    - user

- name: Check if user exists
  getent:
    database: passwd
    key: "{{ user.name }}"
  register: user_exists
  tags:
    - user

- name: Prompt for user password
  prompt:
    msg:
      say: "Enter desired user password"
      ask: user_password
  when: "user_exists.msg is defined"
  tags:
    - user

- name: Create user and assign to group
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    password: "{{ user_password|password_hash('sha512') }}"
    update_password: on_create
    uid: "{{ user.uid }}"
    append: true
  when: "user_exists.msg is defined"
  tags:
    - user

- name: Create user log dir
  file:
    path: /home/{{ user.name }}/{{ user.log.dir }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: user.log.dir is defined
  tags:
    - user

- name: Push logrotate config for user logs
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/user
  when: user.log.dir is defined
  tags:
    - user

- name: Create user socket directory
  file:
    path: /run/user/{{ user.uid }}
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0700
  tags:
    - user

- name: Start user systemd instance
  systemd:
    name: "user@{{ user.uid }}"
    state: started
  notify: stop systemd per-user instance
  tags:
    - user
