---
- name: Overwrite os-release
  copy:
    src: os-release
    dest: /usr/lib/os-release

- name: Overwrite arch-release
  copy:
    content: ""
    dest: /etc/arch-release
    force: true
    group: root
    owner: root
    mode: 0644

- name: Remove Antergos packages
  pacman:
    name:
      - antergos-mirrorlist
      - antergos-alerts
      - antergos-common-meta
      - antergos-desktop-settings
      - antergos-gnome-meta
      - antergos-gnome-defaults-list
      - antergos-keyring
      - antergos-midnight-timers
      - gnome-shell-extension-status-menu-buttons
      - numix-icon-theme-square
      - numix-icon-theme
      - pamac
    state: absent

- name: Remove Antergos repository
  blockinfile:
    path: /etc/pacman.conf
    state: absent
    block: |
      [antergos]
      SigLevel = PackageRequired
      Include = /etc/pacman.d/antergos-mirrorlist

- name: Remove backup boot entry
  file:
    path: /boot/loader/entries/antergos-fallback.conf
    state: absent

- name: Check if bootentry exists
  stat:
    path: /boot/loader/entries/antergos.conf
  register: boot_entry

- name: Move main boot entry
  copy:
    remote_src: true
    src: /boot/loader/entries/antergos.conf
    dest: /boot/loader/entries/arch.conf
  when: "boot_entry.stat.exists == True"

- name: Remove old boot entry
  file:
    path: /boot/loader/entries/antergos.conf
    state: absent

- name: Rename boot entry
  replace:
    path: /boot/loader/entries/arch.conf
    regexp: "Antergos"
    replace: "Arch Linux"

- name: Update default boot entry
  replace:
    path: /boot/loader/loader.conf
    regexp: "antergos"
    replace: "arch"
