---
- name: Install hdparm
  pacman:
    name: hdparm
    state: present

- name: Check for TRIM support
  shell: "hdparm -I /dev/sda | grep TRIM"
  register: hdparm
  ignore_errors: true
  changed_when: false

- name: Enable and start weekly filesystem TRIM timer
  systemd:
    name: fstrim.timer
    enabled: true
    state: started
  when: "hdparm.rc == 0"
