---
- hosts: localhost
  become: true
  vars_files:
    - vars/work.laptop.yml
  roles:
    - { role: timezone, tags: ['timezone'] }
    - { role: locale, tags: ['locale'] }
    - { role: hostname, tags: ['hostname'], when: 'hostname is defined' }
    - { role: bumblebee, tags: ['bumblebee'] }
    - { role: base, tags: ['base'] }
    - { role: networkmanapger, tags: ['networkmanager'] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: mirrorlist, tags: ['mirrorlist'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: dns, tags: ['dns'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: firejail, tags: ['firejail'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: spell, tags: ['spell'] }
    - { role: docker, tags: ['docker'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: azure, tags: ['azure'] }
    - { role: k8s, tags: ['k8s'] }
    - { role: node, tags: ['node'] }
    - { role: java, tags: ['java'] }
    - { role: cups, tags: ['cups'] }
    - { role: urlwatch, tags: ['urlwatch'] }
    - { role: gdm, tags: ['gdm'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: sound, tags: ['sound'] }
    - { role: bluetooth, tags: ['bluetooth'], when: 'bluetooth is defined' }
    - { role: browsers, tags: ['browsers'] }
    - { role: teams, tags: ['teams'] }
    - { role: office, tags: ['office'] }
    - { role: vscode, tags: ['vscode'] }
    - { role: intellij, tags: ['intellij'] }
    - { role: vpn, tags: ['vpn'] }
    - { role: calibre, tags: ['calibre'] }
    - { role: media, tags: ['media'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: work, tags: ['work'] }
    - { role: gaming, tags: ['gaming'] }
