---
- name: Install freetype2
  pacman:
    name: freetype2

- name: Install cairo
  pacman:
    name: cairo

- name: Install fontconfig
  pacman:
    name: fontconfig

- name: Enable LCD filter
  file:
    src: /etc/fonts/conf.avail/11-lcdfilter-default.conf
    dest: /etc/fonts/conf.d/11-lcdfilter-default.conf
    state: link

- name: Enable sub-pixel rendering
  file:
    src: /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link

- name: Enable hinting
  file:
    src: /etc/fonts/conf.avail/10-hinting-slight.conf
    dest: /etc/fonts/conf.d/10-hinting-slight.conf
    state: link

- name: Push font substitutions
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf

- name: Install core fonts
  pacman:
    name:
      - cantarell-fonts
      - gsfonts
      - noto-fonts
      - tex-gyre-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-joypixels
      - ttf-liberation
      - ttf-roboto
      - ttf-ubuntu-font-family

- name: Install AUR fonts
  aur:
    name: "{{ item }}"
  become: true
  become_user: "{{ user.name }}"
  loop:
    - nerd-fonts-fira-code
    - nerd-fonts-fira-mono
    - ttf-caladea
    - ttf-carlito
    - ttf-courier-prime
    # - ttf-heuristica
    - ttf-impallari-cantora
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-opensans
    - ttf-oswald
    - ttf-quintessential
    - ttf-signika
    - ttf-symbola
  tags:
    - aur

- name: Enable JoyPixels font
  file:
    src: "../conf.avail/75-joypixels.conf"
    dest: /etc/fonts/conf.d/75-joypixels.conf
    state: link
    force: true
